// Code generated by MockGen. DO NOT EDIT.
// Source: writer.go
//
// Generated by this command:
//
//	mockgen -source=writer.go -destination=mock_database_test.go -package=database
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	clickhouse "github.com/ClickHouse/clickhouse-go/v2"
	driver "github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	gomock "go.uber.org/mock/gomock"

	circuitbreaker "github.com/activecm/rita/v5/circuitbreaker"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Breaker mocks base method.
func (m *MockDatabase) Breaker() *circuitbreaker.Breaker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Breaker")
	ret0, _ := ret[0].(*circuitbreaker.Breaker)
	return ret0
}

// Breaker indicates an expected call of Breaker.
func (mr *MockDatabaseMockRecorder) Breaker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Breaker", reflect.TypeOf((*MockDatabase)(nil).Breaker))
}

// GetContext mocks base method.
func (m *MockDatabase) GetContext() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockDatabaseMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockDatabase)(nil).GetContext))
}

// QueryParameters mocks base method.
func (m *MockDatabase) QueryParameters(arg0 clickhouse.Parameters) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryParameters", arg0)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// QueryParameters indicates an expected call of QueryParameters.
func (mr *MockDatabaseMockRecorder) QueryParameters(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryParameters", reflect.TypeOf((*MockDatabase)(nil).QueryParameters), arg0)
}

// getConn mocks base method.
func (m *MockDatabase) getConn() driver.Conn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getConn")
	ret0, _ := ret[0].(driver.Conn)
	return ret0
}

// getConn indicates an expected call of getConn.
func (mr *MockDatabaseMockRecorder) getConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getConn", reflect.TypeOf((*MockDatabase)(nil).getConn))
}
